In [ ]:
import numpy as np

Create a list with the names of every planet in the solar system (in order)

In [15]:
planets = ["Mercurio", "Venus", "Marte", "Tierra", "Jupiter", "Saturno", "Urano", "Neptuno"]

In [16]:
print(planets)

['Mercurio', 'Venus', 'Marte', 'Tierra', 'Jupiter', 'Saturno', 'Urano', 'Neptuno']


In [17]:
type(planets)

list

Have Python tell you how many planets there are by examining your list

In [18]:
size = len(planets)
print(size)

8


Print the first four planets in the solar system (the rocky planets)

In [19]:
print(planets[0:4])

['Mercurio', 'Venus', 'Marte', 'Tierra']


Imprimir el nombre del planeta que tiene una s al final de su nombre

In [32]:
letter = input("Letter: ")[0] # Limit to one character
words = input(planets).split()
for word in words:
    if letter in word:
        print(word, end="")
print() # Add newline

Letter: s
['Mercurio', 'Venus', 'Marte', 'Tierra', 'Jupiter', 'Saturno', 'Urano', 'Neptuno']Venus
Venus


2° Task

Asignar el dato recibido a una variable.

In [21]:
T = 30.3

Aplicar la transformación de unidades usando esta variable.
Save the data in Celsius in another variable.

In [22]:
C = 5/9*(T-32)

Use the print function to display both results.


In [23]:
print(T)

30.3


In [24]:
print(C)

-0.9444444444444441


3° TASK

In [25]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [26]:
reshape = array.reshape(4,4)

In [27]:
print(reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


4° TASK

Cree un array con los ángulos mencionados en grados.

In [36]:
angulos = np.array([0,30,45,60,90])

Convierta los ángulos a radianes.

In [41]:
import math
print(math.radians(angulos[1]))
print(math.radians(angulos[2]))
print(math.radians(angulos[3]))
print(math.radians(angulos[4]))

1.5707963267948966


5° Task

Now, read the numpy documentation to find a function to calculate  𝑑𝑑𝑥𝑦(𝑥𝑖)

In [44]:
np.gradient?