In [2]:
import numpy as np

Create a list with the names of every planet in the solar system (in order)

In [9]:
planets = ["Mercurio", "Venus", "Marte", "Tierra", "Jupiter", "Saturno", "Urano", "Neptuno"]

In [10]:
print(planets)

['Mercurio', 'Venus', 'Marte', 'Tierra', 'Jupiter', 'Saturno', 'Urano', 'Neptuno']


In [11]:
type(planets)

list

Have Python tell you how many planets there are by examining your list

In [12]:
size = len(planets)
print(size)

8


Print the first four planets in the solar system (the rocky planets)

In [13]:
print(planets[0:4])

['Mercurio', 'Venus', 'Marte', 'Tierra']


Imprimir el nombre del planeta que tiene una s al final de su nombre

In [14]:
letter = input("Letter: ")[0] # Limit to one character
words = input(planets).split()
for word in words:
    if letter in word:
        print(word, end="")
print() # Add newline

IndexError: string index out of range

Correccion: 

In [15]:
letter = "s"
for planet in planets: 
    if letter in planet:
        print(planet)

Venus


2° Task

Asignar el dato recibido a una variable.

In [16]:
T = 30.3

Aplicar la transformación de unidades usando esta variable.
Save the data in Celsius in another variable.

In [17]:
C = 5/9*(T-32)

Use the print function to display both results.


In [18]:
print(T)

30.3


In [19]:
print(C)

-0.9444444444444441


3° TASK

In [20]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
reshape = array.reshape(4,4)

In [ ]:
print(reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


4° TASK

Cree un array con los ángulos mencionados en grados.

In [ ]:
angulos = np.array([0,30,45,60,90])

Convierta los ángulos a radianes.

In [ ]:
import math
print(math.radians(angulos[1]))
print(math.radians(angulos[2]))
print(math.radians(angulos[3]))
print(math.radians(angulos[4]))

1.5707963267948966


Correccion de tutora: 

In [ ]:
angulos = np.array([0,30,45,60,90])
angulos_rad = np.deg2rad(angulos)

5° Task

Now, read the numpy documentation to find a function to calculate  𝑑𝑑𝑥𝑦(𝑥𝑖)

In [ ]:
np.gradient?